# Tensorflow Quick Start Beginner

In [1]:
import tensorflow as tf
import numpy as np
import pandas as pd

In [2]:
mnist = tf.keras.datasets.mnist
print(mnist)

<module 'tensorflow.keras.datasets.mnist' from '/usr/local/lib/python3.6/dist-packages/tensorflow/keras/datasets/mnist/__init__.py'>


In [4]:
(X_train, y_train), (X_test, y_test) = mnist.load_data()
X_train, X_test = X_train / 255, X_test / 255

11493376/11490434 [==============================] - 0s 0us/step


In [3]:
model = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(input_shape=[28, 28]),
    tf.keras.layers.Dense(128, activation='relu'),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(10)
])

In [6]:
predictions = model(X_train[:1]).numpy()
predictions

array([[ 0.16309488, -0.02382639,  0.38048908,  0.10963561, -0.26838654,
        -0.07074537, -0.33657047, -0.2743826 ,  0.05817072,  0.00916373]],
      dtype=float32)

In [7]:
tf.nn.softmax(predictions).numpy()

array([[0.11804365, 0.09791827, 0.14670865, 0.11189884, 0.0766748 ,
        0.09343016, 0.07162106, 0.07621642, 0.10628565, 0.10120248]],
      dtype=float32)

In [8]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)
loss_fn

In [9]:
loss_fn(y_train[:1], predictions).numpy()

2.370541

In [10]:
y_train[:1]

array([5], dtype=uint8)

In [11]:
predictions

array([[ 0.16309488, -0.02382639,  0.38048908,  0.10963561, -0.26838654,
        -0.07074537, -0.33657047, -0.2743826 ,  0.05817072,  0.00916373]],
      dtype=float32)

In [12]:
model.compile(optimizer='adam', loss=loss_fn, metrics=['accuracy'])

In [13]:
model.fit(X_train, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.4859 - accuracy: 0.8580
Epoch 2/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.1508 - accuracy: 0.9561
Epoch 3/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.1089 - accuracy: 0.9672
Epoch 4/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.0855 - accuracy: 0.9745
Epoch 5/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.0737 - accuracy: 0.9766


In [14]:
model.evaluate(X_test, y_test, verbose=2)

313/313 - 0s - loss: 0.0728 - accuracy: 0.9774


[0.07277663797140121, 0.977400004863739]

In [16]:
probability_model = tf.keras.models.Sequential([
    model,
    tf.keras.layers.Softmax()
])

In [17]:
probability_model.compile(optimizer='adam', loss=loss_fn, metrics=['accuracy'])
probability_model.fit(X_train, y_train)

1875/1875 [==============================] - 4s 2ms/step - loss: 1.4903 - accuracy: 0.9775


In [19]:
probability_model(X_test[:5]).numpy()

array([[2.20596053e-09, 7.04486518e-14, 1.85368432e-08, 7.24242568e-07,
        1.10010426e-15, 2.36467823e-09, 6.70315363e-18, 9.99999285e-01,
        1.48387036e-09, 5.81891957e-09],
       [2.22223472e-11, 1.81587808e-07, 9.99999762e-01, 3.93610300e-08,
        5.78100940e-21, 1.35186946e-08, 5.14320357e-11, 6.13131654e-19,
        4.90651186e-10, 5.88021191e-19],
       [3.42239548e-09, 9.99964237e-01, 7.52695905e-06, 4.39968034e-07,
        2.17086836e-07, 2.54888107e-07, 2.08033200e-07, 2.31200374e-05,
        3.89850493e-06, 6.93745283e-10],
       [1.00000000e+00, 1.47796479e-17, 3.25629768e-09, 2.69667448e-12,
        4.71989781e-10, 6.72352538e-12, 3.92437229e-08, 1.05287743e-08,
        1.55659209e-12, 2.91109248e-09],
       [2.30007990e-09, 4.57394446e-15, 2.44250797e-09, 4.65813048e-11,
        9.99418139e-01, 1.22777075e-11, 2.32708586e-09, 1.75791243e-07,
        1.14954157e-09, 5.81723871e-04]], dtype=float32)

In [23]:
np.argmax(probability_model(X_test[:5]).numpy(), axis=1)

array([7, 2, 1, 0, 4])