# FreeCodeCamp: Core Learning

---

## Introduction to Tensorflow

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import tensorflow as tf

In [ ]:
sekar = tf.Variable('Sekardayu Hana Pradiani', tf.string)
print(sekar)

<tf.Variable 'Variable:0' shape=() dtype=string, numpy=b'Sekardayu Hana Pradiani'>


In [ ]:
saskia = tf.Variable('Saskia Nurul Azhima', tf.string)
print(saskia)

<tf.Variable 'Variable:0' shape=() dtype=string, numpy=b'Saskia Nurul Azhima'>


In [ ]:
arifa = tf.Variable('Arifa Rachma', tf.string)
print(arifa)

<tf.Variable 'Variable:0' shape=() dtype=string, numpy=b'Arifa Rachma'>


In [ ]:
nums = tf.Variable([1, 2, 3], tf.int32)
print(nums)

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([1, 2, 3], dtype=int32)>


In [ ]:
bunch_of_ones = tf.ones([3, 2, 1])
print(bunch_of_ones)

tf.Tensor(
[[[1.]
  [1.]]

 [[1.]
  [1.]]

 [[1.]
  [1.]]], shape=(3, 2, 1), dtype=float32)


In [ ]:
tf.rank(bunch_of_ones)

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [ ]:
bunch_of_ones.shape

TensorShape([3, 2, 1])

In [ ]:
tf.reshape(bunch_of_ones, [-1])

<tf.Tensor: shape=(6,), dtype=float32, numpy=array([1., 1., 1., 1., 1., 1.], dtype=float32)>

In [ ]:
flatten_ones = tf.reshape(bunch_of_ones, [-1])
print('flatten_ones', flatten_ones)
print('flatten_ones shape', flatten_ones.shape)

flatten_ones tf.Tensor([1. 1. 1. 1. 1. 1.], shape=(6,), dtype=float32)
flatten_ones shape (6,)
